version: '3.1'

services:
  jedox:
    build:
      context: .
    ports:
      - 80
      - 7777
      - 7775
    volumes:
      - ./share:/usr/share
      # - ./work:/usr/src/work
    # restart: always
